export const GET_ALL_STORE_SAGA = 'GET_ALL_STORE_SAGA'

export const GET_ALL_STORE = 'GET_ALL_STORE'

export const GET_ALL_STORE_AND_PRODUCT_SAGA = 'GET_ALL_STORE_AND_PRODUCT_SAGA'

export const GET_ALL_STORE_AND_PRODUCT = 'GET_ALL_STORE_AND_PRODUCT'